apiVersion: v1
kind: Service
metadata:
  name: webhook-service
  namespace: my-namespace
  labels:
    app: node-validation-webhook
spec:
  selector:
    app: node-validation-webhook
  ports:
  - port: 443
    targetPort: 8443
    name: https
  type: ClusterIP
